# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'CAWReader' do
pod 'Alamofire'
pod 'JSONModel'
pod 'SnapKit'
pod 'Kingfisher'
pod 'EDStarRating'
pod 'TagListView'
pod 'MJRefresh'
pod 'WSProgressHUD'
pod 'FrameAccessor'
pod 'CryptoSwift'
pod 'pop'
pod 'Reveal-iOS-SDK', '~> 1.6.2'
end

